#! /usr/bin/php -q
<?php

<<<<<<< HEAD
// Read AllStar database
//$url = "https://allstarlink.org/cgi-bin/allmondb.pl";
=======
// Code refactored / debugged by KB4FXC, 11/06/2018.
// Fixed issue where error conditions were always generated by private nodes.

// Updated to check for strictly private nodes
// and change load order - private first
// WA3DSP 2/2016
// $Id $

// Original code by WD6AWP
// Modified to run immediately when called directly
// and load randomly within  30 minute window when
// called by cron

// Refactor to use CURL --- KB4FXC 11/19/2018

/* Refactored 2020-02-29 WD6AWP
   - Use file_get_contents for $url
   - Comment HamVoIP url
   - Add $dir for storage location
   - Reformat indentation
   - Minor edits to messages
 */

$dir = getcwd() . "/";
$db = $dir . "astdb.txt";
$privatefile = $dir . "privatenodes.txt";

$retries = 0;
$Pcontents = '';
$private = getenv('PRIVATE_NODE');
$contents = '';
$contents2 = '';

#$url = "https://allstarlink.org/cgi-bin/allmondb.pl";
$url2 = "https://nodelist.hamvoip.org/getASLdb.php";
>>>>>>> 8333bafbf0a8735befdb86e3144eaf0823c621f1
$url = "http://allmondb.allstarlink.org/";
$astArr = file($url);

// Read private nodes
$privatefile = "privatenodes.txt";
$privateArr = array();
if (file_exists($privatefile)) {
    $privateArr = file($privatefile);
}

// Merge with private nodes
if (!empty($privateArr)) {
    $fileArr = array_merge($astArr, $privateArr);
} else {
    $fileArr = $astArr;
}

// Sort
natsort($fileArr);

// Output
$db = "astdb.txt";
if (! $fh = fopen($db, 'w')) {
    die("Cannot open $db.");
}
if (!flock($fh, LOCK_EX))  {
    echo 'Unable to obtain lock.';
    exit(-1); 
}
foreach($fileArr as $line) {
    if (strlen(trim($line)) == 0) {
        continue;
    }
    fwrite($fh, $line);
}
fclose($fh);
?>
